name: Build and Push Docker Image

on:
  push:
    branches:
      - devops
      - cicd
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build api Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/wireapps-api:2.0 ./api

      - name: Push api Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/wireapps-api:2.0
      
      - name: Build web Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/wireapps-web:2.0 ./web

      - name: Push web Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/wireapps-web:2.0
